### ISSUE TITLE
Use fn.toString() and preserve line breaks.

### ISSUE THREAD

**Issue by kimfucious** [react-syntax-highlighter/react-syntax-highlighter#241]
This is not a bug, or at least I don't think it is.  It's a usage question, so feel free to tell me to buzz off and post on stackoverflow if you want.

In brief, say I have a function like the below:

```js
export const fn = () => {
      let sum = 0;
      for (let i = 0; i < 1000; i++) {
        if (i % 3 === 0 || i % 5 === 0) {
          sum += i;
        }
      }
      return sum
};
```
And I want to get that into a React component (via props) and then display that function with your marvelous tool, like this:

```jsx
import React from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { okaidia } from "react-syntax-highlighter/dist/esm/styles/prism";

export const DisplayFunction = ({ fn }) => {
  return (
    <SyntaxHighlighter language="javascript" style={okaidia}>
      {fn.toString()}
    </SyntaxHighlighter>
  );
};
```

Things actually look pretty good in dev mode (i.e. npm start in a create-react-app).  The styling is there and line-breaks look good.  But when I push this to production, the build process removes the line breaks, causing the (still styled with lovely colors) text to display on a single line.

What I'm doing now is copying functions to a string literal and then using that instead of `fn.toString()`, which is starting to become tedious and the reason for my question.

Thanks in advance for any insight you might have.

**Comment by simmerer** [comment]
Great question!

This is a build-level issue, where you need to tell your javascript-modifying webpack plugin to buzz off for only certain lines... which I don't think is possible in the tools I'm familiar with.

I don't know if you're using `uglify` or `terser` in your config, but assuming you're relying on `terser` to compress your javascript, [the compression options there](https://github.com/terser/terser#compress-options) seem to indicate that you could add `inline: false` to prevent line-break removal across all your javascript code.

You'd need something like this in order to do away with creating string literals:

```js
export const fn = () => {
/* minify-disable */
      let sum = 0;
      for (let i = 0; i < 1000; i++) {
        if (i % 3 === 0 || i % 5 === 0) {
          sum += i;
        }
      }
      return sum
/* minify-enable */
};
```

But I don't know of any minifiers that provide such an option.
