### ISSUE TITLE
Custom language highlight 

### ISSUE THREAD

**Issue by Stevemoretz** [react-syntax-highlighter/react-syntax-highlighter#322]
**Is your feature request related to a problem? Please describe.**
I've written a compiler myself I wanna syntax highlight it.

**Describe the solution you'd like**
I'd like to syntax highlight via regex.

**Describe alternatives you've considered**
Nothing really.

**Comment by simmerer** [comment]
Hey @Stevemoretz - that's awesome!

This isn't really the repo for it, though, because RSH pulls all of its languages and styles from whatever's bundled in [Highlight](https://highlightjs.org/) and [Prism](https://prismjs.com/) (well, and some additional [Prism themes](https://github.com/PrismJS/prism-themes)).

Highlight isn't accepting any more core languages, and has switched to recommending people generate third-party packages. Check out [Prism's guide to contributing new language definitions](https://prismjs.com/extending.html#creating-a-new-language-definition), though... that might be the best place for you to start.
