### ISSUE TITLE
Rename androidstudio.js to android-studio.js

### ISSUE THREAD

**Issue by sahithyandev** [react-syntax-highlighter/react-syntax-highlighter#328]
All of the styles (expect *androidstudio*) are named in a uniform way, where words are joined with a `-` and lowercased.
Eg: `atom-one-dark.js`

**Describe the solution you'd like**
The solution is simple, Rename the file `androidstudio.js` to `android-studio.js`. Doing this will ensure uniformity among the styles. But also note that it may cause problems for most of the dependants.

**Describe alternatives you've considered**
This is not a problem. So leaving it as it is, won't cause any problems.

**Additional context**
As I said before, I understand this renaming endeavor may break things which would cause so many problems for the dependants. So if you don't want to rename the file, just close the issue.

*I am not good at writing issue reports or feature requests. So forgive me for all of my errors.*

**Comment by conorhastings** [comment]
These are built by a script and named automatically based on their highlight js name, when the highlight.js name uses a space a - is added, since no space exists in highlight.js the automated script will not add a dash, the overhead requireed seems too much for the benefit gained. See screenshot below from highlight.js docs list of styles
<img width="194" alt="Screen Shot 2020-10-28 at 1 51 15 AM" src="https://user-images.githubusercontent.com/8263298/97413627-411ae080-18c0-11eb-8a03-2ddb0a28b06c.png">
