### ISSUE TITLE
SPARQL language does not work

### ISSUE THREAD

**Issue by giacomoronconiobda** [react-syntax-highlighter/react-syntax-highlighter#470]
**Describe the bug**
Trying a simple SPARQL query does not highlight any keyword-
```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX swrlb: <http://www.w3.org/2003/11/swrlb#>
PREFIX swrl: <http://www.w3.org/2003/11/swrl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX : <http://www.obdasystems.com/books/>

select distinct ?x ?t ?n ?penName {
  ?x a :Book;
     :title ?t;
     :writtenBy ?a.
  ?a ^:actAsAuthor ?p.
  ?p :name ?n.
  optional{?a :penName ?penName.}
}
```
**To Reproduce**
No errors shown.

**Expected behavior**
Should highglight something (eg vaiables, keywords)

**Comment by simmerer** [comment]
Hello! You'll need to explicitly use [Prism](https://github.com/react-syntax-highlighter/react-syntax-highlighter#prism) instead of the default Highlight for this language.

- refractor (prism) supports SPARQL: https://github.com/wooorm/refractor/blob/main/lang/sparql.js
- highlight does not: https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md
